//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Class_Project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        public int id { get; set; }
        public int house_number { get; set; }
        public string street_name { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public Nullable<int> number_of_rooms { get; set; }
        public Nullable<int> number_of_bathrooms { get; set; }
        public Nullable<int> garage { get; set; }
        public Nullable<int> pool { get; set; }
        public Nullable<int> fireplace { get; set; }
        public Nullable<decimal> price { get; set; }

        public static List<House> get_house(string where_key = "1", string where_value = "1")
        {
            return House_Data.get_house(where_key, where_value);
        }

        public static bool Save_house(House house)
        {
            return House_Data.Save_house(house);
        }

        public static List<city> get_cities()
        {
            return House_Data.get_cities();
        }

        public static List<state> get_states()
        {
            return House_Data.get_states();
        }

        public static List<country> get_countries()
        {
            return House_Data.get_countries();
        }
    }
}
