//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Class_Project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int role { get; set; }

        public static bool Register(User user)
        {
            return User_Data.Register(user);
        }

        public static bool Login(string username, string password)
        {
            return User_Data.Login(username, password);
        }
    }
}
